# ansible-playbook -i $HOST, playbooks/setup-user.yml -u $USER -k --ask-become-pass
- name: Setup user login
  hosts: all
  become: true
  become_method: su
  become_user: root
  tasks:
    - name: Install sudo
      apt:
        update_cache: yes
        name: "sudo"

    - name: Allow 'sudo' group to have passwordless sudo
      copy:
        content: "%sudo ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/sudo_nopasswd
        mode: 0440
        validate: "/usr/sbin/visudo -cf %s"

    - name: Add login user to sudo group
      user:
        name: "{{ansible_ssh_user}}"
        groups: sudo
        append: yes
        state: present
        createhome: yes

    - name: Set up authorized keys for the login user
      authorized_key: user={{ansible_ssh_user}} key="{{item}}"
      with_file:
        - ~/.ssh/id_ed25519.pub

    - name: Disable root login over SSH
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      notify:
        - restart sshd

    - name: Disable password login
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
